#!/usr/bin/env bash

function justkill()
{  pkill -f routekeysloop.sh
   pkill '^routekeys$'
}
[ "$1" == "justkill" ] && { justkill ; exit 0; }

arch=$(uname -m)
srcbin=bin/$arch
srcscr=scripts
dstbin=/usr/bin

[ -f $srcbin/routekeys ] || { echo "routekeys for arch: $arch not compiled"; exit; }

justkill

cp -v $srcbin/routekeys $dstbin
cp -v $srcscr/*.sh $dstbin

#this script is separated from makefile for possibility of installing
#on system without make tools (if target arch binary compiled and exists)
